import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    display: 'flex',
    flex: 1,
    backgroundColor: '#F5F5F5',
    alignItems: 'center',
  },
  containerHeader: {
    width: '100%',
    height: '10%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#4682B4',
  },
  textHeader: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 18,
  },
  containerInfos: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-around',
    //backgroundColor: 'rgba(176, 196, 222, 0.44)',
    paddingVertical: 25,
    width: '100%',
  },
  textInfos: {
    color: '#4682B4',
    fontWeight: 'bold',
    fontSize: 16,
  },
  containerForm: {
    marginTop: 15,
    //backgroundColor: 'rgba(176, 196, 222, 0.44)',
    width: '90%',
    borderRadius: 5,
    padding: 20,
  },
  titleForm: {
    fontSize: 18,
    fontWeight: 'bold',
    //color: '#000',
  },
  containerInputs: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inputNumber: {
    display: 'flex',
    marginTop: 30,
    backgroundColor: '#ECECEC',
    alignSelf: 'center',
    paddingHorizontal: 12,
    width: '45%',
    height: 45,
    borderRadius: 5,
  },
  input: {
    marginTop: 30,
    backgroundColor: '#ECECEC',
    alignSelf: 'center',
    paddingHorizontal: 12,
    width: '100%',
    height: 45,
    borderRadius: 5,
  },
  camera: {
    marginTop: 30,
    backgroundColor: '#ECECEC',
    alignSelf: 'center',
    paddingHorizontal: 12,
    width: '100%',
    height: 45,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btnContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 30,
  },
  btnCollection: {
    padding: 15,
    backgroundColor: 'green',
    borderRadius: 10,
    width: '46%',
    alignItems: 'center',
  },
  btnText: {
    color: '#FFF',
    fontWeight: 'bold',
  },
});
